### ISSUE TITLE
Reconsider prefix/suffix separator

### ISSUE THREAD

**Issue by lanthaler** [json-ld/json-ld.org#132]
A lot of the reluctance to use prefixes stems from the fact that the separator we use (a colon ":") that can't be used in variable names in any programming language I'm aware of. We never discussed this before as we blindly chose to use the colon as the separator by following what RDF, XML, etc do. I think however, for JSON-LD it might make much more sense to use another separator. Unfortunately there are not many alternatives available.

One possible alternative would be to use the dollar sign ($). This would work for C, C++ (most compilers support it), Java, and JavaScript. The other potential character to be used as separator is the underscore ("_") which would be usable in almost every programming language. I don't know if potential collisions would be a real issue (it is often used instead of a whitespace) but the use of two underscores would help to prevent this.

So, I think we should discuss which one of the following forms should be used for compact IRIs:

```
a) prefix:suffix
b) prefix$suffix
c) prefix_suffix
d) prefix__suffix
```

Pros of changing the separator:
- allow compact IRIs to be directly used in (most) programming language

Cons:
- potentially breaks a lot of existing JSON-LD documents - this shouldn't be a huge issue just yet but as we longer we wait, the more critical this will become

**Comment by linonetwo** [comment]
I'm trying to adapt JSON-LD in TiddlyWiki, but field name in it can't have colon, because each file in tiddlywiki will be serialized to yaml-like syntax:

```
field: value
```

So I search around the internet to find a solution and found this. It is sad that you didn't allow it alias `:` to `_` or `$` in 2012, so we can't use it in 2023...

Is it too late to change this? But anyway, it seems ok to use `_` instead while not affect the semantic of JSON-LD (As you have consider using `_` as alias, this means it is harmless). So I'm gonna use `_` instead of `:` in TiddlyWiki ecosystem, for this moment...

**Comment by gkellogg** [comment]
Many feel that the compact IRI syntax which uses ':' is not really good for idiomatic JSON-LD. In fact, I believe it's mostly used for representing IRIs when coming from other RDF serializations.

The ':' as separator really comes up when compacting IRIs where there is a suitable namespace term to use. You can, of course, use "_" as part of a term, and if you use `@vocab`, you can set it as something like `"@vocab": "http://example.com/vocab_"`, which will then interpret vocabulary-relative terms (such as keys and `@type` using this, so that if you had a key "foo", it could expand to `"http://example.com/vocab_foo"`, although it won't compact back to "foo" unless it is explicitly defined as a term.
