### ISSUE TITLE
Framing shouldn't introduce new blank node identifiers

### ISSUE THREAD

**Issue by lanthaler** [json-ld/json-ld.org#293]
[Raised by Robert Sanderson](http://lists.w3.org/Archives/Public/public-linked-json/2013Jul/0143.html):

[...] not naming blank nodes would also be another nice output option, rather than generating explicit bnode names [when framing a document].

**Comment by gkellogg** [comment]
Perhaps another cleanup step at the end of framing (perhaps at the end of compaction) that would remove blank node identifiers as values of `@id` if they are only used once.

**Comment by dbooth-boston** [comment]
We actually need this for a project now, and were working around it by filtering them out after framing if they were only used once.  Unfortunately we implemented the work-around before we noticed this issue.

**Comment by lanthaler** [comment]
Interesting. David could you expand a little on why you needed to do that?On Jan 9, 2017 20:31, David Booth <notifications@github.com> wrote:We actually need this for a project now, and were working around it by filtering them out after framing if they were only used once.  Unfortunately we implemented the work-around before we noticed this issue.

**Comment by dbooth-boston** [comment]
We are doing round-trip testing, in which we translate from one RDF data model to another, and then back again to verify that no information was lost.  The original data is in JSON-LD.  We use framing to put it back into the original JSON-LD format (other than property ordering), so that we can simply do a JSON-diff on the result to detect any deviations from the original.

The workaround makes a pass through the JSON-LD counting blank node references, and then comes back and deletes any that appear only once.

**Comment by gkellogg** [comment]
As @dbooth-boston notes, algorithmically removing unnecessary blank nodes is easy enough. We already have a pass where we transform `@preserve` values, and could possibly roll BNode removal in there.

It should be controlled by an API option (pruneBlankNodeIdentifiers). I'd default it to `true`, but that's a matter of opinion.

**Comment by dbooth-boston** [comment]
Is there a plan on the horizon for implementing this feature?  If it would be helpful, we could potentially contribute a PR for it.  But if you were planning to implement it soon anyway, that is probably easier, since you obviously know your code base far better than we do.  What do you think @gkellogg ?

**Comment by gkellogg** [comment]
@dbooth-boston Sorry for the delay, working on the feature now.

**Comment by dbooth-boston** [comment]
Hi Gregg,

Thanks for addressing this!   We wanted to try it out, but we were 
unable to find the actual code that implements it.  It does not seem to 
be appear in the commit that you cited, though we do see the option and 
the documentation.  Where is the code for it?

thanks,
David Booth

**Comment by dbooth-boston** [comment]
I've implemented this in the Ruby implementation in this commit: https://github.com/ruby-rdf/json-ld/commit/b76c51f9bc1b585db899cfaccc80d57013b5a3f6

Gregg Kellogg

**Comment by dbooth-boston** [comment]
Any plans to add this to the JavaScript implementation?   Or would you 
recommend that we try to do it an submit a pull request?

thanks,
David Booth

**Comment by dlongley** [comment]
@dbooth-boston, we will add it eventually to jsonld.js, but that usually means me doing the implementation and I'm swamped with other work for while. PRs are always welcome of course if you need to get the feature in sooner.
