### ISSUE TITLE
Visualization of graph for playground

### ISSUE THREAD

**Issue by msporny** [json-ld/json-ld.org#383]
From @pchampin:

> it would be nice if the JSON-LD playground had a tab with graphical representation like the one on RDFa.info .
> I'm currently using both websites for teaching linked data to my students, and that would help me greatly explain how different concrete syntaxes convey the same abstract syntax.

from @bollwyvl:

> In a visualizer for the playground, I'd like more than just the straight json tree diagram or rdf hairball diagram, or maybe have some options.
> - I'd like to see contexts as regions enclosing node-ified edges.
> - I'd like color to correspond to the prefixes...
> - And use prefixes, but maybe only on a legend
> - I'd like to know when an edge with an @container is a set vs list vs index... shape?
> - I'd like to search/filterable
>   Dagre-d3, webcola and klayjs-d3 would all be interesting choices... They each have strengths, but can all do the region thing.

**Comment by elf-pavlik** [comment]
:+1: we also gathered links to various graph visualization libraries in https://github.com/uf6/design/issues/9
WebVOVL looks very cool http://vowl.visualdataweb.org/webvowl/index.html
![WebVowl](http://vowl.visualdataweb.org/webvowl/webvowl.png)

**Comment by elf-pavlik** [comment]
Promising code: https://github.com/scienceai/jsonld-vis

@darobin  might help - https://twitter.com/robinberjon/status/700516898245582848

**Comment by pchampin** [comment]
Very cool. Thanks


On 26 Jan 2017 9:52 p.m., "Manu Sporny" <notifications@github.com> wrote:

Closed #383 <https://github.com/json-ld/json-ld.org/issues/383> via #459
<https://github.com/json-ld/json-ld.org/pull/459>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/json-ld/json-ld.org/issues/383#event-938424742>, or mute
the thread
