### ISSUE TITLE
recommend escaping for dangerous HTML embedding

### ISSUE THREAD

**Issue by graingert** [json-ld/json-ld.org#390]
The valid JSON-LD document:

``` json
{
  "@context": "http://json-ld.org/contexts/person.jsonld",
  "@id": "http://dbpedia.org/resource/John_Lennon",
  "name": "</script><script>alert('foo');</script><script>",
  "born": "1940-10-09",
  "spouse": "http://dbpedia.org/resource/Cynthia_Lennon"
}
```

Becomes dangerous when embedded in HTML:

``` html
<script type="application/ld+json">
{
  "@context": "http://json-ld.org/contexts/person.jsonld",
  "@id": "http://dbpedia.org/resource/John_Lennon",
  "name": "</script><script>alert('foo');</script><script>",
  "born": "1940-10-09",
  "spouse": "http://dbpedia.org/resource/Cynthia_Lennon"
}
<script>
```

Hypertext authors should use something like  https://gist.github.com/RandomEtc/2657669 to produce:

``` html
<script type="application/ld+json">
{
  "@context": "http://json-ld.org/contexts/person.jsonld",
  "@id": "http://dbpedia.org/resource/John_Lennon",
  "name": "\u003c/script\u003e\u003cscript\u003ealert('foo');\u003c/script\u003e\u003cscript\u003e",
  "born": "1940-10-09",
  "spouse": "http://dbpedia.org/resource/Cynthia_Lennon"
}
<script>
```

**Comment by msporny** [comment]
Good point @graingert - we had always considered that this sort of processing is outside of the purview of the JSON-LD core algorithms. Note that the content that you have in the second code block is invalid JSON-LD (and JSON, for that matter). One could construct JSON-LD that is valid though, with the same sort of "attack" you mention above.

I think the problem here is the same problem with cutting and pasting anything from the Web into your page; don't do it unless you know what you're pasting into your code.

It's difficult to know what "dangerous" HTML is and what it isn't. So, we'd have to scan every value. Scanning every value of a JSON-LD document would consume a very large amount of CPU resources, so we shouldn't do that either. We could provide an option, but then I imagine that most people wouldn't use it (because it requires understanding why the code above is dangerous and most developers that blindly cut-paste code don't understand why they'd need the feature).

Did you have thoughts on what feature should be included and how it would be enabled given the restrictions I've mentioned above?

**Comment by graingert** [comment]
@msporny I don't mean the second code block to be invalid JSON, can you tell me where this is and I'll fix it?  It's a copy-paste of block 1 (which is valid): It's only invalid when embedded in an HTML document.

Yes, when escaping you have to process every code-point: escaping a string is a perfectly reasonable operation for web servers: eg in https://gist.github.com/RandomEtc/2657669

This should go in the spec under http://www.w3.org/TR/json-ld/#embedding-json-ld-in-html-documents to replace "Depending on how the HTML document is served, certain strings may need to be escaped."

**Comment by gkellogg** [comment]
As an alternative, surround the JSON-LD with "", which is safe from everything that doesn't contain an end comment, which is both unlikely and easy to scan for.

**Comment by graingert** [comment]
@gkellogg nope because "<!--" is invalid JSON. JSON must start with a "{" or a "["

paste the following into https://developers.google.com/structured-data/testing-tool/
```html
<script type="application/ld+json">
<!--
{
  "@context": "http://schema.org",
  "@type": "Organization",
  "url": "http://www.example.com",
  "logo": "http://www.example.com/images/logo.png"
}
-->
</script>
```

**Comment by gkellogg** [comment]
That would be a bug in the testing too, IMO. The Linter handles this properly. Traditionally, this is how to protect content within a script block.

In my case, this is detected in my RDFa processor, which extracts leading and trailing escapes and CDATA before processing it off to the JSON-LD processor; it does the same for Turtle or any other detected script type.

**Comment by graingert** [comment]
support for HTML or HTML escaping is not in JSON-LD spec, and this this linter behaves correctly

CDATA doesn't work in this case because:
* CDATA is only appropriate for making it easier for humans to insert unescaped content into XML documents because you cannot escape the end-token `]]>` Eg: my user changed their name to `"]]></script><script>alert('foo')';</script><script><![CDATA["`
* Google incorrectly does not support CDATA in JSON-LD documents

```html
<script type="application/ld+json">
<![CDATA[{
  "@context": "http://schema.org",
  "@type": "Organization",
  "url": "http://www.example.com",
  "logo": "http://www.example.com/images/logo.png"
}]]>
</script>
```

**Comment by gkellogg** [comment]
@graingert I was only suggesting the CDATA, as it may occur in XHTML, and certain tools won't work properly if processing an XHTML document as XML and the content is not escaped using CDATA. For this reason, my processor will look for it and remove it if found before handing off; I wasn't suggesting that we recommend the use of CDATA.

Other than adding something to the json-ld.org site describing escaping of JSON-LD in HTML documents, this discussion might be better moved to public-vocabs@w3.org, as it mostly concerns best practices for publishing such JSON-LD, and the ill-behavior of the SDTT called out and fixed. (See existing thread [HTML Entities and Escaping in JSON-LD Literals](https://lists.w3.org/Archives/Public/public-vocabs/2015Jun/0010.html).

**Comment by lanthaler** [comment]
@graingert's example with the unicode escapes is completely valid. @msporny, why do you think that

>  the content that you have in the second code block is invalid JSON-LD (and JSON, for that matter).

JSON-LD processors (or better already the JSON parser) should decode those characters properly. We shouldn't introduce workarounds like `<!-- -->` in HTML. [My JSON-LD processor handles the escapes just fine](http://www.markus-lanthaler.com/jsonld/playground/?json-ld=%7B%0A%20%20%22%40context%22%3A%20%22http%3A%2F%2Fschema.org%2F%22%2C%0A%20%20%22%40id%22%3A%20%22http%3A%2F%2Fdbpedia.org%2Fresource%2FJohn_Lennon%22%2C%0A%20%20%22name%22%3A%20%22%5Cu003c%2Fscript%5Cu003e%5Cu003cscript%5Cu003ealert('foo')%3B%5Cu003c%2Fscript%5Cu003e%5Cu003cscript%5Cu003e%22%2C%0A%20%20%22born%22%3A%20%221940-10-09%22%2C%0A%20%20%22spouse%22%3A%20%22http%3A%2F%2Fdbpedia.org%2Fresource%2FCynthia_Lennon%22%0A%7D&frame=%7B%7D&context=%7B%7D&startTab=tab-expanded) (please note I changed the context because json-ld.org seems to be down at the moment). I'm sure the other processors handle it as expected as well because this is how JSON works.

@graingert adding an example to the spec wouldn't hurt, I agree. On the other hand, this is exactly the same as with plain JSON. Thus, some languages (like PHP with it's [JSON_HEX_TAG](http://php.net/manual/en/json.constants.php#constant.json-error-unsupported-type)) even have built-in support for this.

**Comment by gkellogg** [comment]
I propose closing this issue; please 👍 or 👎.

**Comment by graingert** [comment]
@gkellog ah bummer!

**Comment by graingert** [comment]
@gkellogg ah bummer!

**Comment by gkellogg** [comment]
@graingert It's not dead, and if someone can come up with text which is generally acceptable, it can be put in. But, it's not something we're actively pursuing for JSON-LD 1.1 right now.
