### ISSUE TITLE
Weird compaction behaviour with "@type": "@vocab"

### ISSUE THREAD

**Issue by letmaik** [json-ld/json-ld.org#400]
Input:
```js
{
  "@context": [
    {
      "hydra": "http://www.w3.org/ns/hydra/core#",
      "property": { "@id": "hydra:property", "@type": "@vocab" },
      "comment": "rdfs:comment"
    }
  ],
  "property": {
    "@id": "http://foo",
    "comment": "foo"
  }
}
```
(produces correct triples)

After compaction with same context:
```js
{
  "@context": {
    "hydra": "http://www.w3.org/ns/hydra/core#",
    "property": {
      "@id": "hydra:property",
      "@type": "@vocab"
    },
    "comment": "rdfs:comment"
  },
  "hydra:property": {
    "@id": "http://foo",
    "comment": "foo"
  }
}
```
Why is the "property" alias not applied here?

When I skip the "comment" field like that:
```js
{
  "@context": [
    {
      "hydra": "http://www.w3.org/ns/hydra/core#",
      "property": { "@id": "hydra:property", "@type": "@vocab" },
      "comment": "rdfs:comment"
    }
  ],
  "property": {
    "@id": "http://foo"
  }
}
```
I get after compaction:
```js
{
  "@context": {
    "hydra": "http://www.w3.org/ns/hydra/core#",
    "property": {
      "@id": "hydra:property",
      "@type": "@vocab"
    },
    "comment": "rdfs:comment"
  },
  "property": "http://foo"
}
```

Is that expected behaviour? Seems very confusing to me and I see more and more contexts using `@vocab` to make life easier, and then this always breaks compaction if more than the ID is included.

**Comment by dlongley** [comment]
@neothemachine,

> Why is the "property" alias not applied here?

Because the value doesn't match the term definition. During compaction, values are compared against term definitions to see if they are proper fits. If a term definition doesn't match, it won't be chosen to associate wit the value.

In this case, because you've defined `property` as `"@type": "@vocab"`, a value must be compactable to a string that represents a URL from a vocabulary. Compacting the value in question here to a string would cause data loss (dropping of `comment`). A rule for Expansion and Compaction is that they will not cause data loss; therefore, the term is not a valid match for the given value and it will not be chosen. The next best term choice is one that is shortened by using a CURIE, which is what it is selected.

Only JSON-LD framing will allow data loss to occur as the result of processing; the use of `"@embed": "@never"` may be an option here.

**Comment by dlongley** [comment]
A more appropriate use of "`@type`: `@vocab`" may be:

```jsonld
{
  "@context": {
    "day": {"@id": "http://example.com/day#", "@type": "@vocab"},
    "Sunday": "day:Sunday",
    "Monday": "day:Monday",
    "Tuesday": "day:Tuesday",
    "Wednesday": "day:Wednesday",
    "Thursday": "day:Thursday",
    "Friday": "day:Friday",
    "Saturday": "day:Saturday"
  },
  "day": "Saturday"
}
```

**Comment by neothemachine** [comment]
If the value doesn't match the term definition in the input example, why is it valid JSON-LD then and the proper triples can be generated? It seems to accept this non-definition-following value but then doesn't do so the other way around. I always thought compaction can get back to the input if the input was valid.

**Comment by dlongley** [comment]
JSON-LD processors try to be lenient with what they accept and strict with what they produce.

That being said, the only thing that `"@type": "@vocab"` tells the processor is this: "When you're expanding the values for the term, if the value is a *string*, then expand it as if it were an `@id` (a URL or a node) instead. Otherwise, expand as usual; the processor will know how to expand because the type can be determined by the form, eg: `{"@id": "obviously_a_node"}`. We're in the "otherwise" case here; your value isn't a string.

So, note that there's nothing illegal about attaching values that aren't strings to terms with type-coercion in their definitions:

```
{
  "@context": {
    "foo": {"@id": "http://example.com/foo", "@type": "http://example.com/datatype"},
    "bar": "http://example.com/bar"
  },
  "foo": [
    "this_is_a_string_so_a_processor_will_expand_to_a_datatype",
    {"@id": "http://example.com/not_a_string_we_know_it_is_a_node", "bar": "some_bar"}
  ]
}
```

In this particular case, you're getting the proper triples because you've supplied a compatible value, just in a different form.

**Comment by neothemachine** [comment]
OK, understand, also why it wouldn't be a good idea to be lenient in compaction etc. It's just a little unfortunate that contexts which are published for a given spec cannot always be used to read back the data in the same lenient way it was written. It seems writing linked data got a lot easier, but processing it is still partly witchcraft. I guess a work-around could be to add a processor option like matchLenient=true.

**Comment by dlongley** [comment]
You can't have it both ways. You'd have to preserve information about how the data was compacted in its expanded form, in order to return it back to its previous state... thereby defeating the purpose of expanded form.
