### ISSUE TITLE
Provide means to get framed output without @graph

### ISSUE THREAD

**Issue by zimeon** [json-ld/json-ld.org#435]
In [email discussion](https://lists.w3.org/Archives/Public/public-linked-json/2016Oct/0035.html) I (@zimeon) suggested that it is helpful to generate simple and clean framed JSON-LD, without the `@graph` structure in cases where it is not necessary, that is easy for JSON-only code to consume. 

The `@graph` structure is added in the second last step of the framing algorithm, and the [pattern suggested in 2013](https://lists.w3.org/Archives/Public/public-linked-json/2013Aug/0001.html) of `compact( frame( flat, frame), context)` to remove it again is wasteful/ugly.

@azaroth42 supports having a means to avoid `@graph`, suggests current behavior could remain default for backwards compatibility.

@gkellogg recalls _"the thought at the time was that a frame could return one or more results, and it would be odd if the results had a different shape depending. However, in my experience, when a frame is used in this context, the user usually knows to expect just a single result"_ and suggests _"Rather than add yet another flag, I would suggest that if the outermost frame in a frame document contains `@graph`, that we ensure that the result does as well, otherwise, only use it if necessary to contain multiple results."_

**Comment by azaroth42** [comment]
From the PR comments, for posterity:

@azaroth42:  Perhaps it's worth flipping the flag to make it easier to understand and make people explicitly get rid of @graph rather than it disappearing magically, compared to 1.0?

> __includeGraph__ (default true)
> If the includeGraph flag is set to false and the processing version is 1.1 or higher, then the "@graph" key will only be included if necessary.

@gkellogg: Presuming that we do set the flag based on the processing mode, then perhaps. However, so much code is out there expecting that the results are under @graph, that we may want to consider having the default be false, and not depend on processing mode, in which case omitGraph may make more sense. Flags that default to true are odd (although we did that for pruneBlankNodeIdentifiers.

@azaroth42: I'm fine with omitGraph default false (agree in retrospect that a default true flag is a bit weird), but I think it should be an error to assert it as true when the processing mode is 1.0
