### ISSUE TITLE
SSL for json-ld.org

### ISSUE THREAD

**Issue by Showcase-Joz** [json-ld/json-ld.org#440]
please consider adding an SSL

Mixed Content: The page at 'https://#########.com/' was loaded over HTTPS, but requested an insecure image 'http://json-ld.org/images/json-ld-button-88.png'.

**Comment by davidlehn** [comment]
The easiest fix is to copy and host that image on your site.

It is difficult to use SSL by default on json-ld.org.  The major issue is that the playground will have mixed content issues when used with SSL.  Many contexts are specified by non-SSL URLs.  Loading them will fail and cause confusion for users.  You would notice the errors if the browser debug console was open but otherwise it will likely fail silently.  A major example of this is the common use of "http://schema.org/".

A possible solution is to support both SSL and non-SSL access.  The playground URL loader could attempt to check for http URLs when using https and put up a warning and link to the http playground.  (Browser handling of redirects may make this difficult or impossible.)  Due to the very common schema.org usage I'm not sure if this would cause more trouble than it's worth.  We could also maybe just host the playground via http and everything else via https.

**Comment by Showcase-Joz** [comment]
Granted its a fix. 

Not going to help with your seo though! And as your looking to become a standard surely this is paramount? 

Also, for the £5 it'll cost, you'll also gain authority for the S part

**Comment by Showcase-Joz** [comment]
Sorry, didn't see the huge reply :/

What about using a single SSL and hosting the playground on a sub domain. Thus not affected by the issue you raised.

**Comment by Showcase-Joz** [comment]
Got it.... 

Use one of these cool new tld. I bet there is a .playground out there!

**Comment by gkellogg** [comment]
@davidlehn I think this is complete now. Close?

**Comment by davidlehn** [comment]
Site is now hosted via https with a proxy to deal with playground issues.
You should still consider hosting images yourself so as not to depend on json-ld.org.
