### ISSUE TITLE
Merge Framing document into API

### ISSUE THREAD

**Issue by gkellogg** [json-ld/json-ld.org#477]
Framing was originally part of the API, but was removed as incomplete before going Rec-track.

**Comment by azaroth42** [comment]
Discussion on 2018-02-05 teleconference resulted in a decision to close the issue without fixing for the following rationale:

* The document becomes quite long, and gives the appearance of additional complexity, even though framing would still be a separate implementation section.  This would be off-putting for new implementers
* Some implementations do not support framing but do support compaction/expansion (e.g. Google's and rdflib-jsonld) and these would suddenly be made non-compliant for an otherwise editorial change
* While the compliance issue can be mitigated by having levels of compliance, this has been actively discouraged as a pattern in the W3C as ...
* ... the testing strategy would be made much more complicated when there are sections of MUSTs that can either be implemented or not. The tools aren't set up for this and it makes it more complicated to see whether or not there are two implementations of every feature. [Admittedly not an issue in our case, as there already are two+ implementations!]

Conclusion: Close Wontfix.

**Comment by dlongley** [comment]
Nevertheless, IMO, we ought to support publishing a separate JSON-LD framing spec as an extension to the API.

**Comment by azaroth42** [comment]
@dlongley Yes, no question about that! This was just that we shouldn't merge the framing spec into the API spec, document wise.
