### ISSUE TITLE
Properties can not be relative IRIs -- requires better documentation

### ISSUE THREAD

**Issue by pchampin** [json-ld/json-ld.org#488]
It recently came as a surprise to me that, in JSON-LD, you can not use a relative IRI as a property. In [this example](http://json-ld.org/playground/#startTab=tab-expanded&json-ld=%7B%22%40context%22%3A%7B%22%40base%22%3A%22http%3A%2F%2Fexample.org%2F%22%2C%22foo%22%3A%22http%3A%2F%2Fexample.org%2Ffoo%22%7D%2C%22foo%22%3A%7B%22%40id%22%3A%22.%2Fbar%22%7D%2C%22.%2Fbaz%22%3A%22hello%20world%22%7D), the key ``"./baz"`` is ignored (although ``"./bar"`` is correctly interpreted as a value of ``@id``).

Then I realized that this is probably a feature, not a bug, and I can see the rationale. After digging into the spec, I also realized that it is indeed documented in the Expansion algorithm (it all comes down to *document relative* defaulting to ``false`` in the IRI Expansion function).

However, I think other people might get confused by it, especially because nothing in the JSON-LD syntax document hints at this. On the contrary, section [5.2](https://www.w3.org/TR/json-ld/#iris) states

> In JSON-LD, IRIs may be represented as an absolute IRI or a relative IRI.

And Section [8.2](https://www.w3.org/TR/json-ld/#node-objects) states:

> All keys which are not IRIs, compact IRIs, terms valid in the active context, or one of the following keywords MUST be ignored when processed:

Ironically, in many other places of the spec, absolute IRIS and relative IRIs are both explicitly mentioned as allowed (e.g. as values of ``@id`` or ``@context``).

The most obvious solution would be to replace "IRIs" by "absolute IRIS", in the sentenced quoted above. I would even argue in favor of a note, drawing the reader's attention to the fact that relatives IRIs as keys are deliberately ignored in JSON-LD.

**Comment by gkellogg** [comment]
A relative IRI may be used as a key, as long as, when expanded, it resolves to an absolute IRI. Practically speaking, this would require an `@vocab` be defined in the context, or that a term which is exactly the same as the IRI be defined.

If this is confusing, it may be worth adding a note to the grammar section.

**Comment by pchampin** [comment]
Terms resolved by ``@vocab`` are not treated as relative IRIs (as far as I can tell, they are simply concatenated), so for me it falls under the category of "terms valid in the active context" -- indeed, a ``@vocab`` makes basically any term valid.

If it was a relative IRI, my understanding is that the ``@base`` would be used to turn it into an absolute IRI; but for keys, this is not the case, ``@base`` is not used. So relative IRIs, as I understand them, are systematically ignored.

**Comment by gkellogg** [comment]
You're correct that `@vocab` is used, but such IRIs are not systmatically ignored, unless there is no value for `@vocab`.

Values interpreted as IRIs fall into two categories: those that are document relative, and those that are vocabulary relative. Properties and values of `@type`, along with terms marked as `@type: @vocab` are vocabulary relative, meaning that they need to either defined terms, a compact IRI, where the prefix is a term, or a relative IRI resolved using `@vocab`.

Looking at the [Expansion Algorithm](http://json-ld.org/spec/latest/json-ld-api/#algorithm-3), you can see in step 8.2 that key is expanded using the  **IRI Expansion algorithm, passing active context, key for value, and true for vocab**.

The [IRI Expansion Algorithm](http://json-ld.org/spec/latest/json-ld-api/#algorithm-2) in step 5 does **If vocab is true, and active context has a vocabulary mapping, return the result of concatenating the vocabulary mapping with value.** Thus a relative IRI is turned into an absolute IRI by concatenating the value to the `@value`. Granted, this does not use normal relative IRI resolution algorithm as in step 6, but it will result in an absolute IRI.

In your example, if the key was "./baz", and `@vocab` was "http://example.com/" the result should be "http://example.com/./baz", which is an absolute IRI.

**Comment by pchampin** [comment]
I see your point, and I could live with that; then your second paragraph above (which is a very clear summary of that point of view) would definitely have to be included somewhere in the spec.

My problem is that several parts of the spec contradict this broader definition of "relative IRI":

Section [1.7](http://json-ld.org/spec/latest/json-ld/#syntax-tokens-and-keywords)
> @base: Used to set the base IRI against which relative IRIs are resolved.

→ Should at least be rephrased to "against which *some* relative IRIs are resolved".

Section [3.2](http://json-ld.org/spec/latest/json-ld/#iris)
> In JSON-LD all relative IRIs are resolved relative to the base IRI.

→ Clearly not *all* of them, only document-relative IRIs, not vocab-relative IRIs.

Section [4.2](http://json-ld.org/spec/latest/json-ld/#base-iri)
> JSON-LD allows IRIs to be specified in a relative form which is resolved against the document base according section 5.1 Establishing a Base URI of [RFC3986].

→ Again, not necessarily the document base. And it is not correct that all relative IRIs are resolved according to RFC3986: vocab-relative IRIs use a simpler algorithm (simple concatenation).

(ibid)
> Setting @base to null will prevent relative IRIs to be expanded to absolute IRIs.

→ Only document-relative IRIs. This won't affect vocab-relative IRIs.

**Comment by gkellogg** [comment]
@pchampin please see if PR #573 addresses your concern; I found the cleanest thing to do was to re-define the term **relative IRI** to make it clear it only refers to things which are relative to the document base, along with some of the explanatory notes you suggested.

**Comment by gkellogg** [comment]
As this issue keeps coming up (see https://github.com/digitalbazaar/jsonld.js/pull/225), perhaps we should consider a syntax to allow proprerties and types to be evaluated relative to the document base, instead of the vocabulary base. For example:

```json
{
  "@context": {"@vocab": "@base"},
  "@id": "#BrewEats",
  "#databaseId": "23987520"
}
```

might resolve both "#BrewEats" and "databaseId" against the document location.

**Comment by pchampin** [comment]
@gkellogg PR #573 makes things much clearer. Thanks.

As for allowing (base-)relative IRIs as ``@type`` values and properties, I think that would indeed meet the expectations of many people -- well, it would meet mine, at least ;-)

My intuition regarding ``@vocab`` is that it exists to allow "prefix-less" terms to be used. Anything containing a slash or a hash *looks* like a relative IRI, and should be treated as such, IMHO (*i.e.* resolved against the base IRI).

Granted, that would break compatibility. Currently:
```json
{ "@context": { "@vocab": "http://example.org/V/", "@base": "http://example.org/B/" },
  "./foo": "bar",
}
```
interprets ``./foo`` as ``http://example.org/V/./foo``; with my proposal, it would now mean ``http://example.org/B/foo``.

But do many people use ``@vocab`` that way? And if they do, do they intend it that way? Especially considering that, from RDF's point of view, ``http://example.org/V/./foo`` [is *not* the same](https://www.w3.org/TR/rdf11-concepts/#dfn-iri-equality) as ``http://example.org/V/foo``? I doubt it, so I could live with this.

**Comment by kidehen** [comment]
@gregg,

My comments on this matter move from https://github.com/digitalbazaar/jsonld.js/pull/225#issuecomment-361336284 to here. 

Fundamentally, this issue is a design bug in JSON-LD with regards to constructing RDF sentences/statements that adhere to Linked Data principles.  There is nothing in RDF that disallows the use of relative HTTP URIs for denoting the predicates of RDF sentences/statements.

**Comment by kidehen** [comment]
@pchampin, 

"IRIs in the RDF abstract syntax must be absolute, and may contain a fragment identifier." specifically refers to the abstract syntax. Thus, as I've stated, we have a bug in JSON-LD in regards to its positioning as a concrete syntax (notation) for crafting RDF sentences in line with Linked Data principles. 

A JSON-LD processor MUST (rather than SHOULD) generate absolute IRIs from document addresses when it encounters relative IRIs in content. Anything less is a vector for:

[1] Confusion
[2] Impeding the very underpinnings of Linked Data deployment using RDF sentences/statements.

**Comment by kidehen** [comment]
@pchampin , 

I can live with [principle of least surprise](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) with Linked Data principles as an example where said surprise currently manifests :)

**Comment by melvincarvalho** [comment]
Relative URIs are kind of a hard core use of RDF, at least, from my limited perspective.

However this is one area where turtle shines.  Others being that you can parse it without needing async functions.  And with upgrade paths to things like TriG and N3.

I've always been curious as to the standing of relative URIs in JSON-LD.  At various times or other I've heard that they can be used or cant be used.  As JSON-LD is quite a long spec, a short summary (or gist) on when and where they can be used in JSON-LD, might be appreciated, by more than just me! :)

**Comment by gkellogg** [comment]
In 1.0, a decision was made on relative URLs, separating document-relative from vocabulary-relative URLs. (some research on resurrecting the decision process is probably in order). Basically, keys and values of `@type` are evaluated relative to any `@vocab` definition in the context (unless specifically defined as terms in the context, or compact IRIs), and values of `@id` are interpreted relative to the document location (which may also be compact IRIs). This is not unlike the way that properties are resolved in RDFa and Microdata.

Another big distinction of JSON-LD compared with Turtle, RDFa and Microdata, is that a context can be a remote document, and does not need to be specified inline. If specified inline, then always resolving relative IRIs to the document is clear, but if it comes form a remote location, the question becomes what is the document location that is used to resolve these things.

Another criteria for JSON-LD is that things that aren't mapped in from the context are dropped, which is useful to allow for specifically ignoring things in JSON documents while extracting those things that are mapped. As a result, if there is no `@vocab` object keys that are not otherwise mapped in the context get dropped, as do their values.

The main distinction is that Turtle allows a prefix to be defined relative to the document, as Kingsley has shown, while JSON-LD doesn't have such a mechanism.

That said, the landscape JSON-LD 1.1 is facing is way beyond that of the 1.0 phase where we were struggling for adoption, and some things might be revisited, when they don't create interoperability issues. Specifically allowing the `@vocab` to be specified as `@base` might be a way to deal with this, and updating the vocabulary-relative IRI handling to use RFC3986 resolution rules, rather than simple string append.

**Comment by gkellogg** [comment]
More to do on this.

**Comment by kidehen** [comment]
@gkellogg,

Okay, I should be much clearer about the fact that my quest is for the use of "relative HTTP URIs" to identify the predicates of RDF statements when using JSON-LD notation :) 

Resolving this is very important. I would like to always provide RDF-Turtle and JSON-LD examples when producing Semantic Web of Linked Data utility demos etc..

**Comment by kidehen** [comment]
@gkellogg,

Do we have any timeframe for implementing the parsing algorithm outlined at https://tools.ietf.org/html/rfc3986#page-30? 

Right now, the issue of relative URIs for denoting RDF sentence predicates remains in limbo.

This is a serious problem.

Kingsley

**Comment by gkellogg** [comment]
@kidehen It's up for discussion on today's CG call. Perhaps a PR with changes ready by the end of the week, depending.

**Comment by gkellogg** [comment]
> Do we have any timeframe for implementing the parsing algorithm outlined at https://tools.ietf.org/html/rfc3986#page-30?

Note that the document-relative IRIs are resolved using this algorithm, your issue is with vocabulary-relative IRIs. In general, changing the algorithm may introduce backwards compatibility issues. However, we're exploring the `"@vocab": "@base"` use case, which would allow relative IRIs to be resolved against the document base (per your examples). In that case RFC3986 resolution probably makes sense.

**Comment by gkellogg** [comment]
[Discussed](https://json-ld.org/minutes/2018-02-26/#topic-4) on call today. __RESOLVED__ to adopt `@vocab`: `@base` gramar, and use RFC3986 resolution in this case.

**Comment by niklasl** [comment]
Mightn't this problem be resolved by simply allowing `@vocab` to be *resolved* against `@base` (instead of requiring it to be a full IRI)? From the examples given, I find that satisfactory, simpler, and most importantly we won't have to tamper with the value space of keys in surprising ways...

**Comment by kidehen** [comment]
@gkellogg,

Re "your issue is with vocabulary-relative IRIs" comment, it is clearer to me for this issue  to be described as being about the ability to identifying the predicate of an RDF sentence/statement using a relative URI. 

I doubt most RDF users and/or developers instinctively realize the existence of this problem -- without it being revealed using my preferred description :) 

Anyway, I anxiously await the bug fix. 

Kingsley

**Comment by gkellogg** [comment]
The example can, indeed, without a `@base` declaration, although we’d need to add text to indicate what the assumed document location was to get the expanded results.

**Comment by gkellogg** [comment]
Kingsley, note that the example was changed in the PR to remove `@base` and describe in prose the document location. Please let us know if you're good with pulling #603 and closing this issue.

**Comment by kidehen** [comment]
@gkellogg ,

Okay for closure. 
Thanks!

**Comment by kidehen** [comment]
@gkellogg ,

Please write out an example of this fix so that I can add it verbatim to my test at: 
http://kingsley.idehen.net/DAV/home/kidehen/Public/Linked%20Data%20Documents/Nanotations/base-test-3.txt

I assume none of the examples in my doc are correct (since they fail my QA), hence my request. 

/cc @TallTed

**Comment by kidehen** [comment]
@gregg,

None of the following work:

```
{
  "@context": {
    "@base": "http://example/document",
    "@vocab": ""
  },
  "@id": "http://example.org/places#BrewEats",
  "@type": "#Restaurant",
  "#name": "Brew Eats"
  …
}
```
or

```
{
  "@context": {
    "@base": "http://example/document",
    "@vocab": ""
  },
  "@id": "http://example.org/places#BrewEats",
  "@type": "#Restaurant",
  "#name": "Brew Eats"
}
```
Please paste something that should work, Ideally something I can test with your online parsers etc..

/cc @TallTed

**Comment by TallTed** [comment]
@gkellogg /cc @kidehen @iherman 

I've just submitted a PR to add the `"@version": 1.1` declaration to the example JSON-LD snippet, as this is necessary for the `"@vocab": ""` to have the desired effect.  I think the following should deliver what we're looking for, once parsers are updated to handle JSON-LD 1.1 --

##### In its own document
```json
{
  "@context": {
    "@version": 1.1,
    "@vocab": ""
  },
  "@id": "http://example.org/places#BrewEats",
  "@type": "#Restaurant",
  "#name": "Brew Eats"
  …
}
```

##### As a paste to the [the dev playground parser](https://json-ld.org/playground-dev/)
```json
{
  "@context": {
    "@version": 1.1,
    "@base": "http://example.com/document"
    "@vocab": ""
  },
  "@id": "http://example.org/places#BrewEats",
  "@type": "#Restaurant",
  "#name": "Brew Eats"
  …
}
```

**Comment by kidehen** [comment]
@gkellogg, 

I am kinda lost right now. Is there a place where one can test closure of this matter? I couldn't get anything going using your distiller either. 

/cc @TallTed

**Comment by gkellogg** [comment]
It shoule either `@version` in context or `processingMode` in maniferst

**Comment by kidehen** [comment]
@gkellogg, 

I can now confirm based on ([my own test setup using our OSDS Browser Extension](https://i.pinimg.com/originals/33/62/41/336241530bbc2815c0adcf292fe8b702.png))  that this matter is now resolved. 
Examples that now work:

```
{
  "@context":
  {
     "schema": "http://schema.org/",
    "@base": ""  
  },
    "@id": "#BrewEats",
    "@type": "schema:Restaurant",
   "#name": "Brew Eats",
    "#databaseId": "23987520"
}
```

OR

```
{
  "@context":
  {
     "schema": "http://schema.org/"

  },
    "@id": "#BrewEats",
    "@type": "schema:Restaurant",
    "#name": "Brew Eats",
    "#databaseId": "23987520"
}
```
