### ISSUE TITLE
Test suite should better support 1.0 libraries.

### ISSUE THREAD

**Issue by davidlehn** [json-ld/json-ld.org#489]
The test suite currently mixes 1.0 and 1.1 tests.  It is difficult to use the test suite with 1.0 libs that have not yet updated to 1.1 support.  There is a "processingMode" option that can be set to json-ld-1.0 or json-ld-1.1 but in some cases this is set to 1.0 on purpose to test 1.1 features (see tp002 and tp005 in https://github.com/json-ld/json-ld.org/blob/master/test-suite/tests/error-manifest.jsonld).  This issue might be resolved with more explicit marking of 1.1 tests separate from the processing mode.

One option might be to add a "version" option for all 1.1 tests so a 1.0 lib could skip all 1.1 tests via a simple filter.  The current "processingMode" would more directly map to the API option of the same name and could perhaps default to the version unless explicitly set otherwise.

See also:
https://github.com/digitalbazaar/jsonld.js/issues/172
https://github.com/digitalbazaar/jsonld.js/pull/179
https://github.com/json-ld/json-ld.org/commit/7374dff787690ce6f7781b1079b9023acf550234#commitcomment-21885156

**Comment by gkellogg** [comment]
The `processingMode` entry has specific meaning for the API, and using `version` might be confusing in a test manifest entry, as it looks like the context `@version`. Suggest using `specVersion`; when not set, it is presumed to be valid for either 1.0 or 1.1 testing. Otherwise, it determines the spec-version being tested.

There are probably some cases where a 1.1 processor will get different results than a 1.0 processor, so may need modes like the following:

* 1.0 only
* 1.1 only
* 1.0+ (maybe use "1.x")

Values probably need to be strings to allow for variations such as `1.x`.
