### ISSUE TITLE
Unexpected behavior of compaction when specifying any @type

### ISSUE THREAD

**Issue by cboettig** [json-ld/json-ld.org#490]
Hi,

When my context includes `@type`, the property is no longer fully compacted.  For example, if the context has the lines
    
    "schema": "https://schema.org",
    "name": {"@id": "schema:name",}

compaction works as expected: a property in the input JSON which uses the prefix, `schema:name`, or the fully expanded `https://schema.org/name` becomes `name`.  However, when I include the expected data `@type` in the argument

    "name": {"@id": "schema:name", "@type": "schema:Text"}
 
Compaction fails to remove the prefix, leaving me with the original `schema:name`.   Here is a [minimal example in JSON-LD Playground](http://tinyurl.com/kyekj4h)

I've read #400, but my understanding there was that the problem arose from the use of `@vocab` Type in particular, rather than the expected type.  My apologies if these are indeed duplicates but I'm not sure how to avoid this issue.

Certainly in this simple example there's no good reason to include the `@type` in the context, but in my own use case is I would like to introduce a custom term in my context and provide an expected Type for it as well, e.g. 

    "readme": {"@id": http://example.org/readme, "@type": "schema:URL"}

where leaving off the type seems undesirable.  How should one go about providing terms with specific types in a context file without breaking the compaction algorithm?

**Comment by gkellogg** [comment]
This is expected behavior; when looking for a term to match a value, the value must _exactly_ match the properties of the term to be used. Your case, your data is in an untyped value ("Jane Doe"), so the `@type` does not match. If the value were `{"@value": "Jane Doe", "@type": "schema:Text"}`, then the `name` property would be selected.

For users of schema.org, this may seem odd, as `schema:Text` could be taken to match such values, but that is not how the algorithms work, and would require some special knowledge. (Even `xsd:string` would not match). The algorithm for selecting a term can be found in the JSON-LD API [Term Selection Section](http://json-ld.org/spec/latest/json-ld-api/#term-selection).

If you change your context to not associate an `@type` with the `name` term, it should be selected.

**Comment by cboettig** [comment]
@gkellogg Thanks so much for your explanation!  Right, I now see that I could have also explicitly included `"name": {"@id": "schema:name", "@type": "schema:Text"}` in the `@context` of the original input document, thus making explicit the fact that the `@type` is consistent, e.g. [like this playground example](http://tinyurl.com/meq4d3d).

Kudos for being such a welcoming community here, I'm much obliged!
