### ISSUE TITLE
Question/ unexpected behavior: Why does compaction sometimes expand and not remove a prefix?

### ISSUE THREAD

**Issue by cboettig** [json-ld/json-ld.org#495]
Consider the following example:

```json
{
  "@context": {
    "schema": "http://schema.org/",
    "ex": "http://example.org/",
    "name": "schema:name",
    "foo": {"@id": "ex:foo", "@type": "schema:Text"},
    "bar": {"@id": "ex:bar", "@type": "schema:Person"},
  },
  "@type": "schema:Thing",
  "name": "Jane Doe",
  "foo": "Professor",
  "bar": {
    "@type": "schema:Person",
    "name": "John Doe"
  }
}
```

Compaction under the identical context results in `bar` being expanded to `ex:bar`, but `foo` remains `foo`.  Why?  To me this is unexpected: the context seems to unambiguously define `bar` as `ex:bar`.  I think this behavior has something to do with `bar` taking a node value rather than a data value, but I fail to see why that matters.  What does the user gain by having it called `ex:bar` that wasn't clear when it was just `bar`?  

This behavior is frustrating from the standpoint of a developer consuming JSON-LD with this kind of context structure, because I feel unable to predict whether the JSON files will use `bar` or `ex:bar` (and naturally I want to just use `bar`, which is why it's explicitly mapped `bar` to `"@id": "ex:bar"` in the first place).  

Here's my example on [Playground](http://tinyurl.com/lkhutdt).

Thanks kindly for any clarification into this seemingly unexpected behavior that is no doubt more a problem of my understanding than algorithmic error!

**Comment by gkellogg** [comment]
@cboettig the `@type` in the context definition for `bar` is actually out of range. `@type` here is intended to describe either a literal datatype, or be one of `@id` or `@vocab`, which determines how values are treated. For literal values, they will compact using the term if the datatype defined for the term is _exactly_ the same as the datatype of the literal value (value object).

In this case, the value is an object, not a literal. One of the object properties is `"@type": "schema:Person"`, this is not a datatype, but an object type. Because the value is not a literal with _datatype_ `schema:Person` (which would not be valid schema.org, in any case), it cannot be used for compaction.

This is described in [Term Selection](http://json-ld.org/spec/latest/json-ld-api/#term-selection), but the language is fairly opaque, and the introduction could use a better english-language overview of what is going on.

I'll keep this open as a reminder to add such language.

**Comment by cboettig** [comment]
@gkellogg thanks so much, that explains volumes.  

Yup, I think there were a few times in the documentation where I've puzzled as to whether the `type` being discussed was in reference only to data type, only to node type, or to both.

**Comment by garpinc** [comment]
@gkellogg I am not understanding above nor did I understand what was described in Term Selection.

What if you want the above to actually work and you want both prefixes to be stripped  (with foo remaining foo and bar remaining bar) ? Then what do you have to do to the context to make that happen?

**Comment by pchampin** [comment]
@garpinc It seems that you are misunderstanding the role of `@type` in a term declaration in the context.
Consider the following term declaration:
```
   "foo":  {
        "@id": "http://example.org/foo",
        "@type": "http://example.orf/bar"
   }
```
means:
* expand a JSON attribute `foo` into the RDF predicate `http://example.org/foo` (this is what `@id` does)
* *if* the value of `foo` is a **string**, *then* expand it into an RDF **literal** with datatype `http://example.org/bar` (this is what `@type` does)

About the second point above, notice that
* if the value of `foo` is not a string (e.g. a number or an object), then the `@type` from the context is ignored;
* in your example above, the `@type` of  `metaDataConcepts` is ignore (since the value of `metaDataConcepts` is an object) and probably **should not** be there (as I understand, `metaframe:ClassConcept` is a class, not a datatype).

So removing it from the context is probably the good solution.

**Comment by garpinc** [comment]
This explanation makes sense. I assume @gkellogg that you agree with this explanation?

I was thinking that @type gives the author of content some indication what to put in the property and some validation facility?

Since this is not the case how does an author know the type by looking at context... And how does a validator know what types are valid?

**Comment by gkellogg** [comment]
@pchampin is correct, of course.

the context is not used for validation, but expansion/compaction. It’s purpose is to provide a “context” for interpreting JSON. An OWL ontology, or ShEx/SHACL shape could be used for validation at the level of RDF, so JSON Schema at the level of JSON.

the Structured Data Linter uses some of these techniques and other heuristics for validating JSON-LD.

**Comment by garpinc** [comment]
Ok.. I think that's pretty clear now... Perhaps some additional verbiage stating what you both said should be in the documentation because clearly what's there now wasn't clear to me.. This was a much better explanation..
