### ISSUE TITLE
Multi-version processing

### ISSUE THREAD

**Issue by azaroth42** [json-ld/json-ld.org#581]
**Issue:**
Currently, it seems that if any context uses `@version: 1.1` then all top level contexts must be 1.1, even though 1.1 is backwards compatible with 1.0.

For example, we have a LONG list of language codes mapped to URIs, like ...
```
{"@context": {
  "en": "http://vocab.getty.edu/aat/300388277"
}}
```

This would be used with @vocab to have the language codes expand to the URIs:

```
{"@context": {
  "language": {"@id": "dct:language", "@type": "@vocab"}
}}
```
We also have a regular 1.0 context that defines a bunch of mappings:

```
{"@context": "https://linked.art/ns/v1/linked-art.json"}
```

But if I want add a replacement context to instead scope the language expansion using 1.1's [scoped contexts](https://json-ld.org/spec/latest/json-ld/#scoped-contexts) feature ...

```
{"@context": [
  "https://linked.art/ns/v1/linked-art.json",
  {"@version": 1.1,
    "language": {"@id": "dct:language", "@type": "@vocab", 
        "@context": "http://linked.art/ns/v1/languages.jsonld"}
  }]
}}
```

then it raises an error, as the top referenced context is 1.0.
This is inconsistent with the scope context (languages.json), which is also 1.0, working fine within the 1.1 context.

This seems at least not great, as there would always need to be two contexts, one for 1.0 and one for 1.1, where the only difference is that the 1.1 context declares itself as such.

**Proposal:** Allow 1.1 contexts to include 1.0 contexts by reference.

**Examples:**

  * Working 1.0 context nested inside 1.1 context:  http://tinyurl.com/ydhnvlvf 
  * Failing 1.0 context in array beside 1.1 context: http://tinyurl.com/y9hws5sw

**Comment by gkellogg** [comment]
This is probably a bug, then. I think the concern is that a 1.0 context may include some 1.1 features and wreck havoc. The spec establishes the processing mode to be 1.0 if not set explicitly, and then fails if it sees a 1.1 version. If you start with 1.1, including 1.0 should not cause any issues, as the processing mode has already been established to 1.1.

In your example, if you invert the order, you'll establish the 1.1 processing mode before getting to the linked-art context, and it should work fine:

```json
{"@context": [
  {"@version": 1.1,
    "language": {"@id": "dct:language", "@type": "@vocab", 
        "@context": "http://linked.art/ns/v1/languages.jsonld"}
  },
  "https://linked.art/ns/v1/linked-art.json"
]
}}
```

That said, we could revisit the danger of this, and not ever establish an implicit processing mode; given that the only valid value of `@version` right now is 1.1, this would never trigger an exception. The possible danger is that the 1.0 context could potentially establish mappings that would have been interpreted differently if it was encountered in 1.1 mode.

Going further, at some point, processors will converge on 1.1, and these explicit announcements and checks become more of an annoyance. The need that sparked it is that 1.0 processors do not look for invalid keywords in term definitions and container values, and could process things differently.

**Comment by azaroth42** [comment]
Ahha. Yes, that's very unintuitive.  A workaround is to put some no-op in an @version: 1.1 context before any other contexts.

**Example:**  Working 1.0 context beside noop 1.1 context http://tinyurl.com/ydehm6ye

**Comment by davidlehn** [comment]
Added this to 1.1 milestone since we're already running into this issue too.

**Comment by dlongley** [comment]
Yeah, issue is biting us. It seems that it would be quite common for people to want to reuse their old 1.0 contexts and add new behavior to them via a 1.1 context. But ... they can't do that without the workaround.

@gkellogg, I read your reasoning for why this error is thrown but didn't quite follow it. Could you provide a concrete example of where something unexpected occurs?

**Comment by gkellogg** [comment]
Quite a long time ago. I think the worry was that a 1.0 context might include some things that you would process differently, had you known you were going to be in 1.1 mode. This was discussed in #446. Note that there isn't a danger for a 1.1 processor operating in 1.0 mode, but for a 1.0 processor silently ignoring 1.1 features.

Thinking about this now, requiring that 1.1 detection happening first might be overkill, and we might consider "upgrading" to 1.1 mode after having started in 1.0. A 1.0 processor would still (as expected/wanted) when it saw the `@version: 1.1`, but this might not happen until later in processing.

I think we can probably relax this check accordingly, without worrying about legacy implementations producing different output.

**Comment by gkellogg** [comment]
The main provision with allowing a 1.1 context after a 1.0 context is that the 1.0 context will be processed with 1.0 rules, but if it were to be seen after a 1.1 context would be processed using 1.1 rules.

Mostly, this relates to determining what terms can be used as compact IRI prefixes; when processing a context in 1.0 mode, any simple term who's value ends with a URI delimiter, or where the term ends with a colon (`:`)  can be used as a prefix; in 1.1, terms need to be defined explicitly using the `@prefix` property in the context definition. This may require that we change to process this based on the `@version` of the context being processed, rather than globally, and that you can't simply set the `processingMode` option in the API to avoid using `@version`. A simpler way to resolve this is to allow any simple term to use the URI prefix and/or term-ending-with-colon rule universally independent of version.

**Comment by gkellogg** [comment]
Looking at my code, it is problematic to process a local context differently, because the `processsingMode` may be set via the API (and is for many tests), so it's difficult to distinguish if it was set to 1.1 via API, or a previously encountered context having an explicit `@version`. The only thing this affects is if an expanded term definition `@id` can be used as a compact IRI prefix in 1.0 mode, which I think is fairly narrow. For example, take the following:

```json
{
  "@context": [
    {"ex1": {"@id": "http://example/"}, "ex2": "http://example/"},
    {"@version": 1.1, "ex3": {"@id": "http://example"}, "ex4": {"@id": "http://example/", "@prefix": true}}
  ]
}
```

Because of the order of processing, but "ex1" and "ex2", in addition to "ex4" may be used as prefixes. If the order is reversed:

```json
{
  "@context": [
    {"@version": 1.1, "ex3": {"@id": "http://example"}, "ex4": {"@id": "http://example/", "@prefix": true}},
    {"ex1": {"@id": "http://example/"}, "ex2": "http://example/"}
  ]
}
```

"ex1" will not be suitable to use as a prefix, because processing mode was already 1.1 when that term definition was encountered.

Rather than suffer the load order ambiguity, I propose that we simply not distinguish between these so that loading order does not matter, and a JSON-LD processor operating in 1.0 mode will not consider using a term with an expanded term definition as a prefix.
