### ISSUE TITLE
Allow @value, @language and @type simultaneously

### ISSUE THREAD

**Issue by azaroth42** [json-ld/json-ld.org#585]
It is currently not possible to have all three of `@value`, `@language` and `@type`.  Meaning that for text with embedded mark up, it is impossible to have both language and format (the datatype given in `@type`) ... neither of which can be reliably introspected from the value.

Any time there is markdown, html, xml, json, yaml, latex, or any other formatting instructions beyond simply print the string to the user, this becomes extremely valuable. Given the usage of those formats on the web, it would enable appropriate management of internationalized texts.

Example:
```
{
  "description": {
    "@value":"<p>Some <b>description</b></p>",
    "@type": "rdf:XMLLiteral",
    "@language" : "en-latn"
  }
}
```

Reference: https://lists.w3.org/Archives/Public/public-linked-json/2014Aug/0031.html
Door-Opened-By: https://github.com/json-ld/json-ld.org/issues/583

**Comment by gkellogg** [comment]
`@format`? Do you mean `@type`?

In your example, how should `"@type": "text/html"` be considered? The value of `@type` is interpreted as an IRI.

In your reference, you use `@type`: `rdf:XMLLiteral` and `@language`. IIRC, when type is `rdf:XMLLiteral` or `rdf:HTML`, the type is taken from the content itself, not what is assigned. RDF doesn't allow the use of a language on a value with a datatype other than `rdf:langString`.

For Turtle, this is dependent on the nodeset having `@xml:lang` attributes added. For RDFa and RDF/XML, it comes from the in-scope value of `@xml:lang`, which gets added to the value through XML Exclusive Canonicalization.

If we address text direction through `rdf:XMLLiteral` and/or `rdf:HTML` datatypes, then adding a language to those literals is inconsistent with the RDF data model. Otherwise, as was suggested in #583, a future RDF may introduce new datatypes for dealing with text direction, which presumably would be compatible with having a language as well.

**Comment by azaroth42** [comment]
I do indeed mean @type and a term not a string. Fixed in the issue to avoid further confusion.

RDF indeed does not allow the use of language on a datatype other than `rdf:langString`, but it's an even more common use case than directionality, which RDF literals also do not support.

For the record, I'm :-1: on this and on #583, for the same reasons.

**Comment by gkellogg** [comment]
Closed in favor of https://github.com/w3c/json-ld-syntax/issues/13.
