### ISSUE TITLE
Should scoped contexts be additive?

### ISSUE THREAD

**Issue by azaroth42** [json-ld/json-ld.org#596]
*Issue*: If two individual contexts define a term mapping with a scoped context, the second scoped context completely replaces the previous scoped context.  This is uninintuitive, given that multiple contexts are additive at the top level.

e.g.

```
{
  "@context": [
  {
    "@version": 1.1,
    "eg": "https://example.org/ns/",
    "foo": {
	  "@id": "eg:foo",
      "@context": [{
        "bar": "eg:bar"
      }]
    }
  },
    {
    "@version": 1.1,
    "foo": {
	  "@id": "eg:foo",
      "@context": [{
        "baz": "eg:baz"
      }]
    }
  },
    {
      "frob": "eg:frob"
    }
 ],
  
  "foo": {
    "bar": "1",
    "baz": "2",
    "frob": "3"
  }
}
```

The result is that `baz` and `frob` are defined but `bar` is not, as the definition of `foo` in the second block erases the definition of `bar`.

*Playground*: http://tinyurl.com/yaoxwmgf

/ht @workergnome

**Comment by gkellogg** [comment]
Contexts do layer, in the first case, you have an array of `@context`, and the second definition replaces the first definition. This doesn't really relate to scoped contexts at all. The first definition of "foo" has a context aliasing "bar" to "eg:bar", and the second defines "baz" as "eg:baz". When you process the second top-level context, it replaces the definition for "foo", including it's embedded context. This would be true for anything else defined on "foo".

Doing something else would change context processing significantly, as the implication would be that term definition merge, rather than being replaced.

This comes from the description of the [Context Processing Algorithm](https://json-ld.org/spec/latest/json-ld-api/#context-processing-algorithm). When encountering a new context, you start by cloning the existing _active context_, you end up processing term definitions in 3.10 by creating new term definitions, thus replacing any that may already exist.

Please suggest some wording that might make this clearer.

**Comment by workergnome** [comment]
Thank you for the explanation--it's not what i intuited happening (which is that the context document associated with the Type or Property would be preserved, and adding new properties to that document in subsequent places would be merged or over-written within that context), but it makes sense.

**Comment by gkellogg** [comment]
As you note, the context is part of the property definition, so in keeping with everything else about replacing term definitions in additive contexts, the included context should be changed as well, at least IMHO. Otherwise, how would you actually replace such a definition. It also begs the question if other attributes of a term definition would service replacement.

The `@context` is part of the term definition, just as is the `@type`, `@language`, `@id`, `@reverse`, `@prefix`, and `@container` properties.

Given your confusion, can you think of something the spec could say which would help with peoples intuition?

**Comment by azaroth42** [comment]
Some possible changes:

4.8:
Replace "The only time that one cannot express a context is inside a context definition itself."
with "The only time that one cannot express a context is as a direct child of another context definition."

To be clear that "inside" now applies only at the first degree, not transitively.

And in 4.14

>  __in exactly the same was__ as if the context were specified within the value itself.

I don't think this is true. Defining the context within the value would not replace the term, and instead the context would be additive.
(note also was -> way typo)

Section 4.2 (sorry to jump back) says correctly:

> If a term is redefined within a context, all previous rules associated with the previous definition are removed.

And 4.14 could remind the reader of this.
