### ISSUE TITLE
Feature request: allow @base in term definitions

### ISSUE THREAD

**Issue by nichtich** [json-ld/json-ld.org#604]
Relative IRIs should be resolved against a base IRI specified in a term definition. For instance:

~~~json
{
  "@context": {
    "@base": "http://example.org/",
    "id": "@id",
    "knows": {
      "@id": "http://xmlns.com/foaf/0.1/knows",
      "@type": "@id",
      "@base": "http://example.com/",
    }
  },
  "id": "alice",
  "knows": "bob"
}
~~~

should expand to:

~~~json
[  {
    "@id": "http://example.org/alice",
    "http://xmlns.com/foaf/0.1/knows": [ {
      "@id": "http://example.com/bob"
   } ]
} ]      
~~~

Note the difference between http://example.org/ and http://example.com/.

**Comment by niklasl** [comment]
I think this makes a lot of sense (I recall similar requests for this in various discussions).

It does however present us with the challenge of allowing `@base` in local contexts even if those are defined in external contexts. I think for security reasons, `@base` can currently only be set (at top level) in a *local* context?

**Comment by azaroth42** [comment]
This is already solved by scoped contexts.

```
{
  "@context": {
    "@version": 1.1,
    "@base": "http://example.org/",
    "id": "@id",
    "knows": {
      "@id": "http://xmlns.com/foaf/0.1/knows",
      "@type": "@id",
      "@context": {
        "@base": "http://example.com/"
      }
    }
  },
  "id": "alice",
  "knows": "bob"
}
```
Works as expected.

**Comment by niklasl** [comment]
Yes, to be clear: I think this is enough to support the requested feature (i.e. we don't need to support it outside of a term-scoped `@context`).

*However*, does it work at all if it is used in a term-scoped context within an external context? The API spec says:
> Please note that `@base` is ignored when processing remote contexts.

If this is the case also for scoped context, should we support it there? And if so, how do we explain the difference in where `@base` in an external context is allowed to have effect (not at top-level but anywhere else)?

It makes sense to support it in external contexts, since I the main use case for scoped contexts, including those using term-specific `@base`, would be to reduced the amount of data transferred (and quite plausibly to add Link-header contexts to existing, custom JSON APIs).

**Comment by azaroth42** [comment]
Agreed. That restriction could be relaxed with a note about the potential issues of importing contexts that define `@base`.

**Comment by nichtich** [comment]
Thanks! I understood "@base is ignored when processing remote contexts" as "@base is only allowed at the root".

**Comment by gkellogg** [comment]
> If this is the case also for scoped context, should we support it there? And if so, how do we explain the difference in where `@base` in an external context is allowed to have effect (not at top-level but anywhere else)?

We should be careful here, as this could introduce a back-door way of modifying the behavior of a document due to a third-party changing a context which includes a term having a scoped context with `@base`.

We could potentially ban the using of `@base` within a scoped context definition, and treat it similarly to the remote context case. Scanning embedded scoped contexts included within a remote context seems challenging.

Another way to solve @nichtich's example would be to define "knows" as `"@type": "@vocab"`, so that "bob" is looked up relative to the vocabulary, rather than the base IRI.

**Comment by azaroth42** [comment]
@gkellogg Could you explain the particular vulnerability? It seems like a remote context could do a LOT of damage by redefining all sorts of things. Why is @base particularly troublesome?

**Comment by gkellogg** [comment]
I don't have time to go into depth on this right now, [it was discussed at length before RDF 1.1 LC2](https://json-ld.org/minutes/2013-05-07/#resolution-2). It seems it wasn't so much as a vulnerability, as weird complexity that could be avoided, and it had precedent in other specs with similar concepts.

Given that `"@type": "@vocab"` addresses many of these use cases, I'm not sure I really see why it's important to re-litigate this.

**Comment by azaroth42** [comment]
Thanks for the pointer! Reading the discussion there, I'm :+1: to leaving this alone.

**Comment by nichtich** [comment]
@gkellogg How can `"@type": "@vocab"` expand a local identifier (`bob`) with a prefix (`http://example.com/`)? Using the current (1.1) online playground I find no solution other than the one provided by @azaroth42. If you don't plan to remove support of `@base` in scoped context, this fully solves my use case.

**Comment by gkellogg** [comment]
Try using “@type”: “@vocab” with a vocabulary definition. 

Apologies, away for the week with very limited bandwidth 

Gregg Kellogg

**Comment by gkellogg** [comment]
@nichtich Now that I'm back in a work environment, here's an example you can try on the playground:

```json
{
  "@context": {
    "@version": 1.1,
    "@base": "http://example.org/",
    "id": "@id",
    "knows": {
      "@id": "http://xmlns.com/foaf/0.1/knows",
      "@type": "@vocab",
      "@context": {
        "@vocab": "http://example.com/"
      }
    }
  },
  "id": "alice",
  "knows": "bob"
}
```

**Comment by gkellogg** [comment]
Issue [discussed on 2018-03-12 meeting](https://json-ld.org/minutes/2018-03-12/#topic-4) where we determined to not fix, as other solutions exist.

However, it did show an issue with `@base` in scoped contexts, which should be illegal.

**Comment by VladimirAlexiev** [comment]
Maybe I'm blind or stupid, but where does https://json-ld.org/spec/latest/json-ld/#typed-values or https://json-ld.org/spec/latest/json-ld/#default-vocabulary describe the use of `"@type": "@vocab"`?

**Comment by VladimirAlexiev** [comment]
Thanks!! Could you please cross-reference this section from the other?
