### ISSUE TITLE
The curious case of ore:Proxy

### ISSUE THREAD

**Issue by azaroth42** [json-ld/json-ld.org#620]
This is documenting the headache that we ran into, for which we do not find a solution. The solvable issues are #616 and #617, but this is part of the background.

The [ore:Proxy class](http://openarchives.org/ore/1.0/vocabulary#proxy) stands for some resource in the context of some set of resources.  It's similar concept to schema.org's `ListItem`, but broader in that it can be any sort of relationship, not just ordering.  In the context of our Museum Collection, a painting might have a particular name.  The same painting in a different collection such as an exhibition hosted by another organization might have a different name.  These contextual assertions can be made against the proxy, rather than being universally true and asserted for the identity of the painting itself.

Enter scoped contexts.  The class of the resource is Proxy.  But it should be able to have only those properties of the resource that it is a proxy for.  If our Object class has a scoped context that defines `part` as the notion of a physical part, and our Text class has a scoped context that defines `part` as the notion of a textual or symbolic part ... and the Proxy class can represent either of those ... there's no way to resolve what `part` means on the Proxy without adding a second `@type` of the class of the resource it is a proxy for.  That's semantically weird, as the Proxy /stands for/ the Object or the Text in a particular context, it isn't an Object or a Text.  It's at best a conceptual or intellectual thing -- our notion of the identity of X as scoped to this particular set of things.

The desirable resolution process would be to take the context of the resource that the proxy is for ... which means first processing the proxy to find that resource and then stepping back to re-process it. Like @dlongley's suggestion of an explicit precedence list, it might be worth discussing, but seems very complicated for an edge case we unfortunately have :(
 
(FYI @workergnome @aisaac @hvdsomp @mart1nkle1n @phonedude @stain)

**Comment by azaroth42** [comment]
A similar situation would be rdf reification, if you wanted to have the value of `rdf:predicate` be scoped by the `rdf:subject` resource in the `rdf:Statement`.

**Comment by aisaac** [comment]
I don't have a fundamental objection to having a second 'real-class' `type` for proxies, which would represent the type of proxied resource. It is a bit strange from a semantic perspective, but come to think of it, when we use other RDF properties on the proxy we ignore that it's a proxy. I.e. a `title` would be 'title T' (of the original resource) not 'Proxy for resource titled T'.
My issue then is that having another type would not really solve the issue. Because when one has such type, then why not having more? I don't see a solid argument against having the resource in your example `rdf:type`d as a Text and a physical Object. And if I understand the starting point well, then we're again in the same situation wrt conflicting aliases.

But now you probably see where I'm getting at: if there are two types that raise a conflict/ambiguity of contexts/aliases, it's probably that something is fishy, and I would let the data publisher/modeler the responsibility of handling this.

**Comment by azaroth42** [comment]
Closing as mostly irrelevant :)
